// tag::main[]

=== Learnings
- **How to parametrize auto-configured beans** (task A)
- **How to create auto-configured beans depending on properties** (task B)

=== Task A

. There's a `GreetingProperties` class in the `{auto-config}` module which should be filled with values from the `application.properties`.

. Annotate the `GreetingAutoConfiguration` with `@EnableConfigurationProperties(GreetingProperties.class)` to enable loading the values from the `application.properties`.

. Annotate `GreetingProperties` with `@ConfigurationProperties` and bind it to the `workshop.greeting` prefix.

. The `StdOutGreetingService` and the `LoggerGreetingService` have constructors which allows you to customize the greeting. By default, it's "Hola", but this should now be configurable via the `application.properties` by setting `workshop.greeting.text`.

. Change the bean methods for `StdOutGreetingService` and `LoggerGreetingService` to inject `GreetingProperties` and configure the greeting prefix.

. Add a property `workshop.greeting.text=Gude` to `application.properties`.

. ✅ Start the application. It should now print _LoggerGreetingService: Gude Spring I/0 Barcelona_ or _StdOutGreetingService: Gude Spring I/0 Barcelona_.


=== Detailed Steps A


.Detailed Steps
[%collapsible]
====


. In `{auto-config}`, annotate `GreetingAutoConfiguration` with:
+
[source,java]
----
@EnableConfigurationProperties(GreetingProperties.class)
----

. In the same module open the `GreetingProperties` class and annotate it with:
+
[source,java]
----
@ConfigurationProperties(prefix = "workshop.greeting")
----

. In `GreetingAutoConfiguration`, inject `GreetingProperties` into both `GreetingService` bean methods:
+
[source,java]
----
GreetingService stdOutGreetingService(GreetingProperties properties)

GreetingService slf4jGreetingService(GreetingProperties properties)
----


. Replace the constructor calls with:
+
[source,java]
----
new StdOutGreetingService(properties.getText())

new LoggerGreetingService(properties.getText())
----

. In `application.properties` set the following:
+
[source,properties]
----
workshop.greeting.text=Gude
----

. Run the application

. ✅ You should see _LoggerGreetingService: Gude Spring I/0 Barcelona_ or _StdOutGreetingService: Gude Spring I/0 Barcelona_ now.


====


=== Task B

. Now, we want a property called `workshop.greeting.type` which controls the type of `GreetingService` that will be used:

- `workshop.greeting.type=logger` should create a `LoggerGreetingService` bean.

- `workshop.greeting.type=stdout` should create a `StdOutGreetingService` bean.

. You can use `@ConditionalOnProperty` for that. Annotate both bean methods with `@ConditionalOnProperty` and set the annotation attributes accordingly.

. Remove the `@ConditionalOnMissingClass` from the `StdOutGreetingService` bean method.

. Add `workshop.greeting.type=stdout` to your `application.properties`

. ✅ Start the application. It should now print _StdOutGreetingService: Gude Spring I/0 Barcelona_.

. Change `workshop.greeting.type` to `logger`.

. ✅ Start the application. It should now print _LoggerGreetingService: Gude Spring I/0 Barcelona_.

. Remove the `workshop.greeting.type` from `application.properties`

. 🤔 Start the application. It now fails. Why is that?

. Change the annotation attributes from `@ConditionalOnProperty` on the `StdOutGreetingService` to also match if the property is missing.

. ✅ Start the application. It should now print _StdOutGreetingService: Gude Spring I/0 Barcelona_.

=== Detailed Steps


.Detailed Steps
[%collapsible]
====

. Annotate the `StdOutGreetingService` bean method with:
+
[source,java]
----
@ConditionalOnProperty(name = "workshop.greeting.type", havingValue = "stdout")
----

. Remove the `@ConditionalOnMissingClass` annotation from the `StdOutGreetingService` bean method

. Annotate the `LoggerGreetingService` bean method with:
+
[source,java]
----
@ConditionalOnProperty(name = "workshop.greeting.type", havingValue = "logger")
----

. In `application.properties` set the following:
+
[source,properties]
----
workshop.greeting.type=stdout
----

. Run the application.

. ✅ You should see: _StdOutGreetingService: Gude Spring I/0 Barcelona_

. In `application.properties` set the following:
+
[source,properties]
----
workshop.greeting.type=logger
----

. Run the application.

. ✅ You should see: _LoggerGreetingService: Gude Spring I/0 Barcelona_
+
TIP: The `LoggerGreetingService` bean will only be created if `library-slf4j` is on the classpath. If not, even `type=logger` will not work.

. Remove the `workshop.greeting.type` line and restart the app.

. Startup of the app fails, because there's no `GreetingService` available. You can use the Conditions Evaluation Report to find out why.

. Change the annotation of the `StdOutGreetingService` bean method in `GreetingAutoConfiguration` to look like this:
+
[source,java]
----
@ConditionalOnProperty(name = "workshop.greeting.type", havingValue = "stdout", matchIfMissing = true)
----

. Run the application.

. ✅ You should see: _StdOutGreetingService: Gude Spring I/0 Barcelona_
====

=== Conclusion

In this exercise, you learned how to read properties from `application.properties` and use the values to configure your beans.
This can not only be used to configure beans, but it can also be used to influence which beans are created at all.

Using `@ConditionalOnProperty`, you can activate specific beans based on the application's configuration, enabling powerful runtime flexibility.
This allows users to influence the behavior using simple property values, without needing to write their own bean overrides.

🤔 Why is this useful in real-world Spring Boot applications?

.Answer
[%collapsible]
====
It allows configuring beans provided through auto-configuration and changing their behavior without the need to change the bean declaration itself.
This enables teams to toggle functionality through properties, and provides sensible defaults with the ability to override them.

An example in Spring Boot would be the `management.server.port` property. If set, an additional webserver is started on the management port which provides access to actuator, etc.
A lot of beans are created under the hood to make that happen, all controlled by a single user-visible property.
====

=== Solution
[source,bash]
....
git checkout -f exercise-6
....

🥳 Superb, let's move on to the next exercise
// end::main[]
