// tag::main[]

Make the `StdOutGreetingService` from `{stdout}` available as an auto-configured Spring bean for applications that rely on `GreetingService`.

=== Learnings
- **How does Spring Boot find auto-configuration classes**
- **How does Spring Boot provide auto-configured beans**
- **How to allow auto-configured beans to be overwritten**

=== Task
. Create an auto-configuration class `com.workshop.magic.config.GreetingAutoConfiguration` in the `{auto-config}` module.

. Add a Maven dependency to `org.springframework.boot:spring-boot-autoconfigure` which brings the `@AutoConfiguration` annotation.

. Add a Maven dependency to other required modules (`{api}` and `{stdout}`). Make them optional, which is a best-practice for auto-configurations.

. Annotate the `GreetingAutoConfiguration` with `@AutoConfiguration`.

. Annotate the `GreetingAutoConfiguration` with `@ConditionalOnClass(GreetingService.class)` to only process the auto-config when `GreetingService` is on the application classpath.

. This auto-configuration should provide `StdOutGreetingService` as a Spring bean of type `GreetingService`. Use the `@Bean` annotation for that.

. Auto-configuration classes must be declared in a classpath resource file named `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`. This file contains fully qualified names of the auto-configuration so that Spring Boot can find them.

. Add the Maven dependency `{auto-config}` and `{stdout}` to `{app}`, making the auto-configured `GreetingService` available.

. 🤔 Starting the application should fail. Why is that?

. To avoid conflicts and allow custom implementations, the `StdOutGreetingService` should only be created when no other bean of type `GreetingService` exists.
This can be achieved by annotating the bean declaration with `@ConditionalOnMissingBean`, which tells Spring Boot to back off when such a bean already exists.

. ✅ Starting the application should now print: _MyGreetingService: Hola Spring I/O Barcelona_.

. Modify the application to use the `StdOutGreetingService` now.

. ✅ Starting the application should now print: _StdOutGreetingService: Hola Spring I/O Barcelona_.

NOTE: Auto-configurations must be loaded only by being named in the imports file. Make sure that they are defined in a specific package space and that they are never the target of component scanning. Furthermore, auto-configuration classes should not enable component scanning to find additional components. Specific @Import annotations should be used instead.

=== Detailed Steps

.Detailed Steps
[%collapsible]
====

. Create a new class `com.workshop.magic.config.GreetingAutoConfiguration` in the `{auto-config}` module.

. Add a Maven dependency to `org.springframework.boot:spring-boot-autoconfigure` in the `{auto-config}` module.

. Add a Maven dependency to `com.workshop:library-stdout` in the `{auto-config}` module, with `<optional>true</optional>`.

. Create a new file `src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` in the `{auto-config}` module (https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.locating-auto-configuration-candidates[see the reference documentation]).

. Add the fully qualified classname of the `GreetingAutoConfiguration` class to the `.imports` file.

. Create a new `GreetingService` bean in `GreetingAutoConfiguration` that returns a new instance of `StdOutGreetingService`. Using the default constructor initializes it with _"Hola"_ as greeting.

. Annotate the `GreetingAutoConfiguration` with `@AutoConfiguration`.

. Add a Maven dependency to `com.workshop:library-autoconfigure` in the `{app}` module.

. Add a Maven dependency to `com.workshop:library-stdout` in the `{app}` module.

. Starting the application fails. That's because there are now two beans of type `GreetingService`: `MyGreetingService` (annotated with `@Service`) from the `{app}` module and the `StdOutGreetingService` from the auto-configuration.

. Use the `@ConditionalOnMissingBean` annotation on the `GreetingService` bean method in `GreetingAutoConfiguration` to only load the bean when no other bean of type `GreetingService` exists (https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.condition-annotations.bean-conditions[see the reference documentation]).

. The application now starts and uses the `MyGreetingService`.

. Now, remove the `MyGreetingService` class from the `{app}` module, or comment out/remove the `@Service` annotation on `MyGreetingService`.

. The application now starts and uses the `StdOutGreetingService`.

====

=== Conclusion
Think for a moment, when is this useful and where does Spring Boot use this concept?

.Answer
[%collapsible]
====
Spring Boot's auto-configuration simplifies application development by automatically configuring components based on the dependencies present on the classpath.
This feature reduces the need for manual setup, allowing developers to focus on business logic rather than boilerplate code.

For example, adding `spring-boot-starter-web` sets up a whole webserver without manual configuration.
====

=== Solution
[source,bash]
....
git checkout -f exercise-2
....

🥳 Fantastic, let's move on to the next exercise
// end::main[]
