// tag::main[]
_Estimated time:  ~10 Min._

Use the Spring Boot configuration processor to generate metadata for your configuration properties.

==== Task

- Add the `org.springframework.boot:spring-boot-configuration-processor` to your project

- Run a build and inspect the `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json` file

🤔 Think about why that file could be useful

- The `text` property in `GreetingProperties`  should be renamed to `prefix`, while deprecating the `text` property. Use `@Deprecated` and `@DeprecatedConfigurationProperty` annotations to achieve this

- Run a build and inspect the file `spring-configuration-metadata.json` again

🤔 What has changed? Why could that be useful?

🤔 Open the `application.properties` in your IDE. Do you notice something?

- Add `org.springframework.boot:spring-boot-properties-migrator` to your app

- Start the app and observe the console output

==== Conclusion

What value is provided by that metadata file? Who could use it?

.Answer
[%collapsible]
====
This metadata file is read by IDEs to provide auto-completion for properties.
Additionally, deprecations and their replacement are also recorded in that file, which is also used by IDEs to guide users.
And the `spring-boot-properties-migrator` also uses this file to display deprecations on startup and to provide the automatic mapping from the old property to the new one.
====


.Detailed Steps
[%collapsible]
====

- Add `org.springframework.boot:spring-boot-configuration-processor` to `components/{auto-config}/pom.xml`, with `optional = true`.
- Configure the `maven-compiler-plugin` to include `org.springframework.boot:spring-boot-configuration-processor` as an annotation processor.
You can take a look at https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.4.5&packaging=jar&jvmVersion=24&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=configuration-processor[the POM file generated by start.spring.io] for an example.
- Run `./mvnw compile` and inspect `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json`.
- Replace `private String text;` in the `GreetingProperties` class with `private String prefix`.
- Annotate the `public String getText()` method with `@Deprecated` and with `@DeprecatedConfigurationProperty(replacement = "workshop.greeting.prefix")`.
- Return `this.prefix` from the `getText()` method.
- Assign `this.prefix` in the `setText()` method.
- Add a new getter and setter method for `private String prefix`.
- Run `./mvnw compile` and inspect `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json`.
- Add `org.springframework.boot:spring-boot-properties-migrator` with `scope = runtime` to `app/app/pom.xml`.
- Run the application

====

==== Solution
[source,bash]
....
git checkout -f main
....
// end::main[]