// tag::main[]

Create unit tests to ensure that the `GreetingAutoConfiguration` works as expected.

=== Task

. A Maven dependency on `org.springframework.boot:spring-boot-starter-test` with scope `test` has to be added in the `{auto-config}` module.

. A test class for the `GreetingAutoConfiguration` class must be created.

. Spring Boot's `ApplicationContextRunner` should be used to test the auto-configuration (https://docs.spring.io/spring-boot/3.3/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.testing[see the reference documentation]).

. AssertJ assertions should be used to verify that the context contains a `StdOutGreetingService` bean if no property is set.

. Implement tests for these use cases:

.. The context contains a `StdOutGreetingService` bean if the property `workshop.greeting.type` is set to `stdout`.

.. The context contains a `LoggerGreetingService` bean if the property `workshop.greeting.type` is set to `logger`.

.. The context contains `BeepGreetingService` bean if the system property `my.custom.condition` is set to `true`.

.. That user-defined beans take precedence over the auto-configured `GreetingService` beans — essentially testing that `@ConditionalOnMissingBean` works.

=== Detailed Steps

.Detailed Steps
[%collapsible]
====
. Add a Maven dependency to `org.springframework.boot:spring-boot-starter-test` with scope `test` to the `{auto-config}` module.

. Create a class named `GreetingAutoConfigurationTest` in `{auto-config}/src/test/java` in the package `com.workshop.magic.config`.

. Create a field of type `ApplicationContextRunner`, and use the fluent API to call `withConfiguration` with `AutoConfigurations.of(GreetingAutoConfiguration.class)`.
+
[source,java]
----
private final ApplicationContextRunner contextRunner = new ApplicationContextRunner()
    .withConfiguration(AutoConfigurations.of(GreetingAutoConfiguration.class));
----

. Write a test case named `shouldProvideStdOutGreetingServiceByDefault` which uses the `run` method of the `ApplicationContextRunner` field.
.. Inside the lambda block of the `run` method, use AssertJ's `assertThat` on the context to call `hasSingleBean` with an `StdOutGreetingService.class` argument.
+
[source,java]
----
@Test
void shouldProvideStdOutGreetingServiceByDefault() {
    this.contextRunner.run(context -> {
        assertThat(context).hasSingleBean(StdOutGreetingService.class);
    });
}
----

. Write a test case named `shouldProvideStdOutGreetingServiceWhenPropertyIsSet` which uses the `withPropertyValues` of the `ApplicationContextRunner` field to set the property `workshop.greeting.type` to `stdout`.
.. Inside the lambda block of the `run` method, use AssertJ's `assertThat` on the context to call `hasSingleBean` with an `StdOutGreetingService.class` argument.
+
[source,java]
----
@Test
void shouldProvideStdOutGreetingServiceWhenPropertyIsSet() {
    this.contextRunner
            .withPropertyValues("workshop.greeting.type=stdout")
            .run(context -> {
                assertThat(context).hasSingleBean(StdOutGreetingService.class);
            });
}
----

. Write a test case named `shouldProvideLoggerGreetingServiceWhenPropertyIsSet` which uses the `withPropertyValues` of the `ApplicationContextRunner` field to set the property `workshop.greeting.type` to `logger`.
.. Inside the lambda block of the `run` method, use AssertJ's `assertThat` on the context to call `hasSingleBean` with an `LoggerGreetingService.class` argument.

. Write a test case named `shouldProvideBeepGreetingServiceIfSystemPropertyIsSet` which uses `withPropertyValues` of the `ApplicationContextRunner` field to set the property `workshop.greeting.type` to `none`.
.. Additionally, it uses the `withSystemProperties` method to set `my.custom.condition` to `true`.
.. Inside the lambda block of the `run` method, use AssertJ's `assertThat` on the context to call `hasSingleBean` with an `BeepGreetingService.class` argument.
+
[source,java]
----
@Test
void shouldProvideBeepGreetingServiceIfSystemPropertyIsSet() {
    this.contextRunner
            .withPropertyValues("workshop.greeting.type=none")
            .withSystemProperties("my.custom.condition=true")
            .run(context -> {
                assertThat(context).hasSingleBean(BeepGreetingService.class);
            });
}
----

. Write a test case named `shouldBackOffIfGreetingServiceIsDefinedByUser` which uses the `withBean` method of the `ApplicationContextRunner` field to define a bean of type `GreetingService`. Create an inner static class or an anonymous class for the "user provided" `GreetingService`.
.. Inside the lambda block of the `run` method, use AssertJ's `assertThat` on the context to call `hasSingleBean` with an `GreetingService.class` argument.
+
[source,java]
----
@Test
void shouldBackOffIfGreetingServiceIsDefinedByUser() {
    this.contextRunner
            .withBean(GreetingService.class, UserGreetingService::new)
            .run(context -> {
                assertThat(context).hasSingleBean(GreetingService.class);
                assertThat(context).hasSingleBean(UserGreetingService.class);
            });
}

    private static class UserGreetingService implements GreetingService {
    @Override
    public void greet(String name) {
        System.out.println("UserGreetingService: Hello " + name);
    }
}
----

====

=== Conclusion

What’s the benefit of writing a unit test for an auto-configuration?

.Answer
[%collapsible]
====
Auto-configurations can contain a lot of conditions, sometimes even custom ones. As this auto-configuration is part of your codebase,
you should also unit-test it to ensure that it behaves as designed, same as the rest of your code.
Spring Boot's `ApplicationContextRunner` makes this easy.
====

=== Solution

[source,bash]
....
git checkout -f exercise-8
....

🥳 Brilliant, let's move on to the next exercise
// end::main[]
