// tag::main[]

Use the Spring Boot configuration processor to generate metadata for your configuration properties.

=== Task

. Add the `org.springframework.boot:spring-boot-configuration-processor` to the `{auto-config}` module.

. Run a build and inspect the `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json` file.

. 🤔 Think about why that file could be useful.

. The `text` property in `GreetingProperties`  should be renamed to `prefix`, while deprecating the `text` property. Use `@Deprecated` and `@DeprecatedConfigurationProperty` annotations to achieve this.

. Run a build and inspect the file `spring-configuration-metadata.json` again.

. 🤔 What has changed? Why could that be useful?

. 🤔 Open the `application.properties` in your IDE. Do you notice something?

. Add `org.springframework.boot:spring-boot-properties-migrator` to the `{app}` module.

. Start the app and observe the console output.

=== Detailed Steps

.Detailed Steps
[%collapsible]
====

. Add `org.springframework.boot:spring-boot-configuration-processor` to `components/{auto-config}/pom.xml`, with `optional = true`.
+
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
----

. Newer Java versions require an explicit configuration for annotation processors. Configure the `maven-compiler-plugin` to include `org.springframework.boot:spring-boot-configuration-processor` as an annotation processor.
You can take a look at https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.4.5&packaging=jar&jvmVersion=24&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=configuration-processor[the POM file generated by start.spring.io] for an example.
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-configuration-processor</artifactId>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
----

. Run `./mvnw compile` and inspect `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json`.

. Replace `private String text` in the `GreetingProperties` class with `private String prefix`.

. Annotate the `public String getText()` method with `@Deprecated` and with `@DeprecatedConfigurationProperty(replacement = "workshop.greeting.prefix")`.

. Return `this.prefix` from the `getText()` method.

. Assign `this.prefix` in the `setText()` method.

. Add a new getter and setter method for `private String prefix`.
+
[source,java]
----
private String prefix = "Hello";

@DeprecatedConfigurationProperty(replacement = "workshop.greeting.prefix")
@Deprecated
public String getText() {
    return this.prefix;
}

public void setText(String text) {
    this.prefix = text;
}

public String getPrefix() {
    return this.prefix;
}

public void setPrefix(String prefix) {
    this.prefix = prefix;
}
----

. Run `./mvnw compile` and inspect `components/{auto-config}/target/classes/META-INF/spring-configuration-metadata.json`.

. Add `org.springframework.boot:spring-boot-properties-migrator` with `scope = runtime` to `app/app/pom.xml`.

. Run the application

====

=== Conclusion

Why is providing that netadata file beneficial? Who would use it?

.Answer
[%collapsible]
====
This metadata file is read by IDEs to provide auto-completion for properties.
Additionally, deprecations and their replacement are also recorded in that file, which is also used by IDEs to guide users.
And the `spring-boot-properties-migrator` also uses this file to display deprecations on startup and to provide the automatic mapping from the old property to the new one.
====

=== Solution
[source,bash]
....
git checkout -f main
....

🥳 Congrats, you finished all exercises! We hope you enjoyed the learnings.

// end::main[]
