// tag::main[]
It's a bit unfortunate that users of your auto-configuration need a dependency on `com.workshop:library-autoconfigure` and on `com.workshop:library-stdout`.

You will now package the `{auto-config}` and `{stdout}` modules into a reusable Spring Boot starter.

=== Learnings
- **How do Spring Boot Starters work**

=== Task:
. Add Maven dependencies to `{auto-config}` and `{stdout}` in the `{starter}` module.
. Add a Maven dependency to `org.springframework.boot:spring-boot-starter` in the `{starter}` module.
. Replace direct dependencies to `{auto-config}` and `{stdout}` in the `{app}` module with the new starter.
. ✅ Confirm that the app still works as expected and prints the greeting.

=== Conclusion
🤔 Why create a starter? When could that be useful?

.Answer
[%collapsible]
====
A starter simplifies the integration of your library.
It contains the auto-configuration and all the needed dependencies in one single dependency.
In our case, the starter only contains two dependencies, but you can image starters for more complex scenarios, which bring dozens or more dependencies.
====

=== Solution
[source,bash]
....
git checkout -f exercise-3
....

🥳 Awesome, let's move on to the next exercise
// end::main[]
